# Generated by Django 2.0.7 on 2018-07-24 02:43

from django.db import migrations
from django.core.management import call_command


def load_data_from_fixture(apps, schema_editor):
    call_command("loaddata", "users")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_data_from_fixture),
    ]
