# Generated by Django 2.1 on 2018-08-22 22:56

from django.db import migrations
from django.core.management import call_command


def create_site(apps, schema_editor):
    call_command("loaddata", "sites")


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_site),
    ]
